###
GET http://127.0.0.1:8080/product http/ 1.1

###
POST http://127.0.0.1:8080/product http/ 1.1
content-type: application/json

{
 "title": "test0909",
 "description": "testtest",
    "params": {
        "price": 101010,
        "availability": true
    }
}